version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: hostel_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: hostel_management
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./Backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - hostel_network

  # Backend API Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: hostel_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3005
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/hostel_management?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
      FIREBASE_PROJECT_ID: your-firebase-project-id
      FIREBASE_PRIVATE_KEY: your-firebase-private-key
      FIREBASE_CLIENT_EMAIL: your-firebase-client-email
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    networks:
      - hostel_network
    volumes:
      - ./Backend/uploads:/app/uploads

  # Frontend Next.js Service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: hostel_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3005/api
      NEXT_PUBLIC_FIREBASE_API_KEY: your-firebase-api-key
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: your-project.firebaseapp.com
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: your-firebase-project-id
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: your-project.appspot.com
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: your-sender-id
      NEXT_PUBLIC_FIREBASE_APP_ID: your-app-id
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - hostel_network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: hostel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - hostel_network

volumes:
  mongodb_data:
    driver: local

networks:
  hostel_network:
    driver: bridge
